config/routes.rb
MonicaSite::Application.routes.draw do
  root to: 'static_pages#home'

  match '/about', to: 'static_pages#about'

  match 'portfolio', to: 'static_pages#portfolio'

  match 'contact', to: 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end

	def about
	end

	def portfolio
	end

	def contact
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Monica Sharma"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright <a href="mailto:monica@monicasharma.me">Monica Sharma</a> 2013.
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Monica Sharma", root_path , id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path, id:"menu" %></li>
          <li><%= link_to "About",    about_path, id:"menu" %></li>
          <li><%= link_to "Portfolio", portfolio_path, id:"menu" %></li>
          <li><%= link_to "Resume", 'Monica-Sharma_Resume.pdf', id: "menu" %></li>
          <li><%= link_to "Blog", 'http://www.sharmachic.com', id:"menu" %></li>
          <li><%= link_to "Contact", contact_path, id:"menu" %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title><%= full_title(yield(:title)) %></title>
  		<link href="http://fonts.googleapis.com/css?family=Lekton" rel="stylesheet" type="text/css">
		<link href="http://fonts.googleapis.com/css?family=Molengo" rel="stylesheet" type="text/css">
  		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
  		<%= stylesheet_link_tag    "application", media: "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
  		<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
  		<!--[if lt IE 9]>
    	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    	<![endif]-->
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<div class="center hero-unit">
<h1>About Me</h1>

<div id="about">
	<table>
	<col style="width:20%">
	<col style="width:80%">
		<tr>
			<td>
				<%= image_tag("monica.png", size:"200x200", alt:"Monica", id:"bio") %>
			</td>
			<td>
				<p>
					A Southern California native with a soft spot for Chicago. I graduated from The University of Southern California with a Bachelors of Arts in Psychology with an emphasis in Behavioral Neuroscience in 2011 and moved to Chicago to complete my Masters of Science in Software Engineering at Loyola University of Chicago in 2013. 
				<p>
					I am a humanitarian with professional experience in user experience research and engineering, project management (technical and non technical), information architecture, web development (java, ruby, rails, HTML/CSS, php, SQL, python), software development, android development, data analysis, scholar level writing and editing. I love working with people and turning ideas into reality. 
				<p>
					I've been a practicing yogini since 2010 and blessed with Coco, the worlds most perfect dog since 2008. I'm an avid travel junkie my list includes countries throughout Asia, Europe, and the Middle East. Always up for an adventure and a trip to anywhere. 
				<p>
					Take a look at my <%= link_to "resume", 'Monica-Sharma_Resume.pdf' %>, <%= link_to "portfolio", portfolio_path %>, and say <a href="mailto:monica@monicasharma.me">hello!</a>


				</p>
			</td>
		</tr>
	</table>
</div>
</div>

app/views/static_pages/contact.html.erb
<div class="center hero-unit">


<h1>Get In Touch With Me!</h1>
<p>
	You can find me on skype! <strong>m0nicasharma</strong><br>
	I also love receiving happy <a href="mailto:monica@monicasharma.me">emails</a><br>
</p>

<div class="contact">
<p>
	Or send me a message!<br> 

	<!-- Do not change the code! -->
<a id="foxyform_embed_link_422087" href="#"></a>
<script type="text/javascript">
(function(d, t){
   var g = d.createElement(t),
       s = d.getElementsByTagName(t)[0];
   g.src = "http://www.foxyform.com/js.php?id=422087&sec_hash=5fcd68b85d1&width=350px";
   s.parentNode.insertBefore(g, s);
}(document, "script"));
</script>
<!-- Do not change the code! -->
</p>
</div>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<h1>Monica Sharma</h1>
<div class="row">
	
		<p>
		<%= link_to image_tag("gh.png", size:"50x50"), 'http://www.github.com/monicasharma1053', target:'_blank' %>
		<%= link_to image_tag("twitter.png", size:"52x50"), 'http://www.twitter.com/monicasharma', target:'_blank' %>
		
		<p>
			<%= link_to image_tag("li.png", size:"48x49"), 'http://www.linkedin.com/in/sharmamonica', target:'_blank' %>
			<%= link_to image_tag("email2.png", size:"55x50"), 'mailto:monica@monicasharma.me' %>
		</p>
	
</div>
<h2>
	Hey there...
</h2>
<p>My name is Monica Sharma and I'm a User Experience Engineer, Information Architect, Developer, Project Manager, and Yogini. I love people, and using data to transform behavior into aesthetically pleasing user-centered design. Explore and <strong><a href="mailto:monica@monicasharma.me">drop me a line</a></strong> if you think we would work well and get along!</p>
</div> 

app/views/static_pages/portfolio.html.erb
<div class="center hero-unit">
<h1>Portfolio</h1>

<table>
<tr>
	<td>
		<%= link_to image_tag("paper.png", size:"120x120"), 'monicasharma_psyc314paper.pdf', target:'_blank' %>
	</td>
	<td>
		<h3><a href="monicasharma_psyc314paper.pdf" target="_blank">The Effects of Yoga Participation on Self Perception and Well Being in Males and Femails</a></h3>
		<strong><h4>Scholarly Article, Research, Data Analysis(SPSS)</h4></strong>
	</td>
</tr>
<tr>
	<td>
		<%= link_to image_tag("mobile.png", size:"100x100"), 'techcocktail.pdf', target:'_blank' %>
	</td>
	<td>
		<h3><a href="techcocktail.pdf" target="_blank">TechCocktail Mobile Application</a></h3>
		<strong><h4>UX Research, Persona creation, Testing, Information Architecture</h4></strong>
	</td>
</tr>
<tr>
	<td>
		<%= link_to image_tag("mobile.png", size:"100x100"), 'storkstack.pdf', target:'_blank' %>
	</td>
	<td>
		<h3><a href="storkstack.pdf" target="_blank">StorkStack Mobile Application</a></h4>
		<strong><h4>UX Research, Flow Diagram, Testing, Information Architecture</h4></strong>
	</td>
</tr>
<tr>
	<td>
		<%= link_to image_tag("browser.png", size:"100x100"), 'http://www.weownitsummit.org', target:'_blank' %>
	</td>
	<td>
		<h3><a href="www.weownitsummit.org" target="_blank">Fouth Annual We Own It Summit Website</a></h3>
		<h4>Website redesign, Development (Ruby/Rails, Twitter Bootstrap, HTML/CSS), User Experience Research</h4>
	</td>
</tr>
<tr>
	<td>
		<%= link_to image_tag("mobile.png", size:"100x100"), 'dga.pdf', target:'_blank' %>
	</td>
	<td>
		<h3><a href="dga.pdf" target="_blank">Democratic Governors Association Mobile Application</a></h3>
		<h4>UX Research, Testing, Flow diagrams, Personas, Information Architecture</h4>
	</td>
</tr>
<tr>
	<td>
		<%= link_to image_tag("browser.png", size:"100x100"), 'http://smart-data-visualization.tumblr.com/post/45866843667/i-took-a-different-spin-on-things-and-implemented', target:'_blank' %>
	</td>
	<td>
		<h3><a href="http://smart-data-visualization.tumblr.com/post/45866843667/i-took-a-different-spin-on-things-and-implemented" target="_blank">SMart Project: Correlations between Individuals and Social Causes</a></h3>
		<h4>Data Visualization, Web Development (d3 framework, Javascript, HTML/CSS), Data Analysis</h4>
	</td>
</tr>
<tr>
	<td>
		<%= link_to image_tag("paper.png", size:"120x120"), 'EZLinks_Features.pdf', target:'_blank' %>
	</td>
	<td>
		<h3><a href="EZLinks_Features.pdf" target="_blank">EZLinks Website Redesign</a></h3>
		<h4>Use Experience Stakeholder Research, Competative Analysis</h4>
	</td>
</tr>
<tr>
	<td>
		<%= link_to image_tag("paper.png", size:"120x120"), 'OD_projectsummary.pdf', target:'_blank' %>
	</td>
	<td>
		<h3><a href="OD_projectsummary.pdf" target="_blank">Overdog Mobile Application Research</a></h3>
		<h4>User Experience Stakeholder Research, Competitive Analysis</h4>
	</td>
</tr>
<tr>
	<td>
		<%= link_to image_tag("browser.png", size:"100x100"), 'http://levelbadger.6te.net/', target:'_blank' %>
	</td>
	<td>
		<h3><a href="http://levelbadger.6te.net/" target="_blank">Level Badger Web Application</a></h3>
		<h4>Password Retrieval Feature Implementation(Ruby/Rails)</h4>
	</td>
</tr>

</table>



</div>